### ISSUE TITLE
Is this project alive ?

### ISSUE THREAD

**Issue by tampler** [paoloboni/binance-scala-client#1]
Tested your ticker example, but it won't work with my API Credentials

**Comment by paoloboni** [comment]
Hi, can you please provide more details on the error you are getting?

**Comment by tampler** [comment]
I created a new project, included your repo and put an example code. I was expecting to see a ticker price in console. But when I start the app with my API credentials, I see a blank console and nothing happens.

I'll publish my test project to demonstrate the issue. Also, may need to do a PR to bump deps

**Comment by paoloboni** [comment]
Had a quick look and the example is not working. Thanks for raising this, will have a better look later today.

**Comment by paoloboni** [comment]
The issue is fixed in v0.0.7 as soon as it becomes available on Nexus.

**Comment by tampler** [comment]
Thanks Paolo
