### ISSUE TITLE
Possible race condition in Integration tests

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#196]
Like many race conditions, this report may be frustratingly hard to reproduce. 
But on my multicore laptop, I can run `testOnly io.github.paoloboni.binance.FapiClientIntegrationTest` and `testOnly io.github.paoloboni.binance.SpotClientIntegrationTest` without problems.

However, if I run `test` I see all sorts of errors from the websocket stream tests. On my system, the two tests run concurrently, eg I see during execution:
```
[info] - it should not rate limit when frequency is lower than limit

  | => io.github.paoloboni.binance.SpotClientIntegrationTest 17s
  | => io.github.paoloboni.binance.FapiClientIntegrationTest 17s
  ```

The errors I see are decoding fails where the test is trying to decode entirely the wrong sort of data, indicating crosstalk with other tests, eg:
```
[io-compute-3] ERROR io.github.paoloboni.Env - Failed to decode frame to scala.collection.immutable.List: {
  "e": "aggTrade",
  "E": 1623095242152,
  "a": 102141499,
  "s": "BTCUSDT",
  "p": "39792.73",
  "q": "10.543",
  "f": 183139249,
  "l": 183139250,
  "T": 1623095241998,
  "m": true
}
```
Thats not a list! ;P

I admit I dont know the details, but I dubious about how concurrent-safe the Wiremock integration is. This feels pretty global to me:
```
package object integration {
  def withWiremockServer(block: WireMockServer => Any) = {
    val wireMockServer = new WireMockServer(options().dynamicPort().dynamicHttpsPort())
    wireMockServer.start()
    block(wireMockServer)
    wireMockServer.stop()
  }
}
```
Can this safely be run over itself? If not, maybe something in the build needs to ensure the two Integration tests are not run concurrently?

**Comment by paoloboni** [comment]
Looking at the snippet above, I'm thinking maybe there's a very narrow time window where the expression `options().dynamicPort().dynamicHttpsPort()` is evaluated by multiple tests at exactly the same time, so the same port is selected from more than one test. Could it be possible?

**Comment by benhutchison** [comment]
Much as I was hoping to report otherwise, the changes don't seem to have resolved the problem I was seeing. You can see my run at https://gist.github.com/benhutchison/0f22aa4d37e79f25f380c359761248a6

**Comment by benhutchison** [comment]
For me, the failures happen on every single run when SpotClientIntegrationTest & FapiClientIntegrationTest run concurrently, so I think a momentary race in options().dynamicPort().dynamicHttpsPort() is unlikely to be causing it.

**Comment by benhutchison** [comment]
But there's a "workaround" of course: I can run the tests independently

**Comment by paoloboni** [comment]
I'm puzzled. Mostly because I don't remember seeing a similar issue neither in CI nor on my machine.

Can you reproduce it consistently at each run now?
Out of curiosity, do you mind sharing some details about your working environment? What OS and JDK are you using?

**Comment by benhutchison** [comment]
I'm on an older 2013 macbook Pro quad core, jdk 17. Yes it happens every
run.

**Comment by paoloboni** [comment]
The CI build runs with JDK 8 and 11. I'm going to try locally to reproduce the problem on JDK 17.

**Comment by paoloboni** [comment]
Ok, I managed to reproduce it on JDK 17 compiling with Scala 3.1.0: https://github.com/paoloboni/binance-scala-client/runs/4795960013?check_suite_focus=true

Can you please confirm what Scala version you are compiling locally when you see this problem?

**Comment by paoloboni** [comment]
Update: this problem appears compiling with Scala 2.x too, but always on JDK 17.

**Comment by benhutchison** [comment]
Jdk17 is the factor! Curious...

**Comment by benhutchison** [comment]
Spent some time investigating this today. Basically replicated your experience:

- on jdk 17, the tests can pass a few times but eventually start to fail. Once failing, they remain failing on reruns until jvm restart.
- on jdk 1.8 graal (another installed java I have) I can't get them to fail.

So it looks like an  intermittent race condition on jdk 17, and some state gets stuck in invalid state until restart. 

Im just`Upgrading openjdk  17.0.1_1 -> 17.0.2`  to see if that's a fix. If not, may have to say "Unssupported on jdk 17 for time being"

**Comment by paoloboni** [comment]
@benhutchison Thanks for the update. I suspect some dependency is subject to some concurrency issue on JDK17 (and probably 16 too?) but never managed to get to a conclusion. Hopefully the problem is in Wiremock (this would mean no issue with the production code) but can't say it right now, so your suggestion of making it clear somehow makes perfect sense.

**Comment by Swoorup** [comment]
Getting odd errors on CI for https://github.com/paoloboni/binance-scala-client/pull/259 for some targets.
Locally everything seems fine.

**Comment by benhutchison** [comment]
@Swoorup previously we had a hypothesis it was somehow related to jdk 17 vs older (eg 8). But your results suggest Scala 3.1 correlates with your issue, since its [happening](https://github.com/paoloboni/binance-scala-client/pull/259/checks) on jdk 8 & 11. May two distinct issues, or a single timing issue, that can be exposed by multiple situations. Think we need to peel some layers off and get closer to the direct cause
