### ISSUE TITLE
Cats Effect 3 support

### ISSUE THREAD

**Issue by DarkWingMcQuack** [paoloboni/binance-scala-client#2]
Hey i just wanted to ask if there are any plans on porting this library to Cats Effect 3.

**Comment by paoloboni** [comment]
Hi @DarkWingMcQuack , I wasn't really planning to do such upgrade. Is it something you would you be willing to help with?

**Comment by DarkWingMcQuack** [comment]
It seems that [log-effect](https://github.com/laserdisc-io/log-effect), and [upperbound](https://github.com/SystemFw/upperbound).
For log-effect there are already pull requests implementing support for CE3, but upperbound didnt have any commits in the recent time and i dont know if there will be support for CE3.

**Comment by paoloboni** [comment]
Cats effect 3 is now available used in v1.0.0
