### ISSUE TITLE
Depth name collision

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#201]
It seems unfortunate that, for just one class in the codebase `Depth`, the parameters and responses have exactly the same name and hence collide, eg on:
```
import io.github.paoloboni.binance.common.parameters._
import io.github.paoloboni.binance.common.response._
```

Elsewhere, params and responses are disambiguated by name, eg `FutureOrderCreateParams` vs `FutureOrderCreateResponse`. I think bringing Depth into line with the convention is worthwhile.

**Comment by paoloboni** [comment]
Hi @benhutchison , thanks for pointing this out
