### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#221]
# CI

The last couple of scheduled CI runs have failed, eg:
```
- queryOrder *** FAILED ***
[info]   sttp.client3.HttpError: statusCode: 400, response: {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}
[info]   at sttp.client3.ResponseAs$.$anonfun$deserializeRightWithError$1(ResponseAs.scala:179)
[info]   at sttp.client3.MappedResponseAs.$anonfun$mapWithMetadata$1(ResponseAs.scala:91)
[info]   at sttp.client3.internal.BodyFromResponseAs.$anonfun$doApply$2(BodyFromResponseAs.scala:24)
[info]   at map @ io.github.paoloboni.binance.spot.SpotApi.$anonfun$createOrder$6(SpotApi.scala:178)
```
PRICE_FILTER suggests the order price is invalid, perhaps too far from current price, or else wrong decimal precision.

# ~Locally~ 

Edit: locally it's just https://github.com/paoloboni/binance-scala-client/issues/196, which is unrelated to price filter, so I wont mention this here.

I'll update this ticket if I make progress on either.

**Comment by paoloboni** [comment]
@benhutchison Thanks for looking into this 🙏 your idea sounds reasonable

**Comment by benhutchison** [comment]
I had a look at why the recent CI was failing. Now its different, the E2E tests for the Futures API which I dont know about:
```
 HttpError: statusCode: 400, response: {"code":-2019,"msg":"Margin is insufficient."}
 ```

**Comment by paoloboni** [comment]
I think the initial problem that led to the opening of this ticket is actually solved.
Regarding this latest failure, I think it's something that has to do with the way the testnet are reset. My balance is currently zero, so there's no way for me to test orders at the moment. (https://dev.binance.vision/t/on-futures-testnet-balance-reduced-90/9053/2)

**Comment by paoloboni** [comment]
The latest failures were fixed with https://github.com/paoloboni/binance-scala-client/pull/301
