### ISSUE TITLE
How is Scala 3 build even working?

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#236]
Hi @paoloboni not a true issue, just raising to have a conversation..

So the client depends upon Enumeratum, for eg `Interval`, which uses Scala 2 macros. Enumeratum doesnt support Scala 3. So how is it possible to compile this project with Scala 3? Don't you see macro errors?

reason I ask is that I tried to upgrade my project that uses this client to Scala 3. And I started see very weird Enumeratum related errors, on calls like `Interval.withNameInsensitive(t.code)`. I had to strip out all usage of the inherited Enumeratum `Enum` methods from my codebase to progress, but ultimately was successful at porting to Scala 3.

But it made me realise there's something missing from my mental model..

**Comment by paoloboni** [comment]
Hey @benhutchison , the Scala 3 build doesn't depend on Enumeratum. There's a bunch of dependencies (including Enumeratum) that are not used for the Scala 3 build: https://github.com/paoloboni/binance-scala-client/blob/b614c31ee4593051057342ba17f598dd98afe78d/build.sbt#L71-L83

The `Interval` enum is implemented in a different way for Scala 3: https://github.com/paoloboni/binance-scala-client/blob/b614c31ee4593051057342ba17f598dd98afe78d/src/main/scala-3/io/github/paoloboni/binance/common/Interval.scala
The client code (common for both Scala 2 and 3 builds) just relies on a common interface and doesn't really know how they are implemented.

**Comment by benhutchison** [comment]
Ah that makes sense now. I was calling code added to Interval by
Enumeratum, then tried to migrate to scala 3. But my ide still resolved the
Scala 2 code, adding further confusion.
