### ISSUE TITLE
Klines start and end times should be optional

### ISSUE THREAD

**Issue by benhutchison** [paoloboni/binance-scala-client#307]
Current param model: `KLines(symbol: String, interval: Interval, startTime: Instant, endTime: Instant, limit: Int)`

However, `startTime` and `endTime` are optional in underlying api, and default to now.
https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data

**Comment by paoloboni** [comment]
Hi @benhutchison, thanks for raising this. Do you have any feedback on #308?
