### ISSUE TITLE
Support for binance futures

### ISSUE THREAD

**Issue by DarkWingMcQuack** [paoloboni/binance-scala-client#31]
Hey, I just wanted to know if you would be interested in adding partial support for binance futures to library. 
I would be glad to help with this as much as I can

**Comment by paoloboni** [comment]
Hi, in general I'm very open to ideas on how to evolve this library. 
I'm aware the set of features provided is very limited, the underlying Binance API layer is providing way more than what this library is currently offering.
It would be great to get some help on it! 🙂 
Re the futures, is there a specific api for them?

**Comment by DarkWingMcQuack** [comment]
I guess critical for usage would being able to cancle open orders on the spot market. Currently orders can only be created, but not cancled.
Yes, futures use another API. [Here](https://binance-docs.github.io/apidocs/futures/en/#) are the official docs, but i usually find it easier to have a look at the [python implementation](https://github.com/Binance-docs/Binance_Futures_python) to see how things work.

**Comment by paoloboni** [comment]
Sounds good. I can see here a list of specs for the future apis: https://binance-docs.github.io/apidocs/spot/en/#futures
Feel free to send PRs for them, perhaps this could be broken down in smaller chunks?

For the order cancellation just created [this](https://github.com/paoloboni/binance-scala-client/issues/32)

**Comment by DarkWingMcQuack** [comment]
perfect, i guess the first design decision would be if we should add something like a `BinanceFutureClient` and a `BinanceFutureConfig`, since the API calls and the config would be different, of if we modify the current `BinanceConfig` to hold the information that the `BinanceClient` can talk to both, the spot and the future api

**Comment by paoloboni** [comment]
Ideally it would be good to keep one client only as it seems that that the API initialisation wouldn't need to change. Rate limits would be calculated based on the combined traffic to the currently used endpoints and the future ones.
Before starting with this it would be good to migrate to the Binance api V3. 
Wdyt?

**Comment by DarkWingMcQuack** [comment]
Yeah i think that is reasonable. Should the client config then always contain both, the spot market api keys and the future market api keys? And what should the client do if he does only have the future api keys, but a method of the spot market api is called?
Regarding the binance api V3, i guess it would be a good idea to migrate the methods which are currently implemented and add some more, but i dont think implementing the whole api should be a top priority. The library is quite usable even without full support over every little thing binance provides.

**Comment by paoloboni** [comment]
Just tried to call `GET /sapi/v1/futures/transfer` (documented [here](https://binance-docs.github.io/apidocs/spot/en/#get-future-account-transaction-history-list-user_data)) using the same api keys I'm using for the other endpoints and it's working.
Do you see a need for using a different set of keys for this apis?

**Comment by DarkWingMcQuack** [comment]
If it it works with the same keys, absolutely not :D. I guess i was just remembering it false then. If it works with the same keys, thats even better. I am sorry for the misinformation :D

**Comment by paoloboni** [comment]
No problem :) can you list here what (futures) endpoints you would suggest to implement first?

**Comment by DarkWingMcQuack** [comment]
At first i guess we should keep the functionality for the spot market in sync with the future market.
So i would propose at first:
+ create order
+ cancle order
+ cancle all orders
+ get orders
+ get balances
