### ISSUE TITLE
Docs or sample code in README.md

### ISSUE THREAD

**Issue by vaibhavbarmy** [paoloboni/binance-scala-client#87]
Hi paoloboni and DarkWingMcQuack, 

First of all thanks for your great efforts I was able to backtest my trading strategy on realtime binance BTCUSDT data. Now am planning to deploy in production for that

Can you guys sample code and how to use it about buying and selling either in docs or README.md

I know development is going at a great pace from your end, but docs will be more helpful. :)

Thanks again
Vaibhav

**Comment by paoloboni** [comment]
Hi @vaibhavbarmy ,
Yes will try to address this soon. Will most likely add documentation to a microsite.

**Comment by vaibhavbarmy** [comment]
Okay thanks a lot, for now can you help me with an error am getting? Below is the code am using

val USDT = balances.balances.filter(_.asset.equals("USDT")).head.free
val createOrderParam = MARKET("USDTBTC", OrderSide.SELL, Option(USDT))
            client.createOrder(createOrderParam)

is giving this error repsonse
{"code":-2014,"msg":"API-key format invalid."}

am able to get prices and balance but not create an order!!!

**Comment by paoloboni** [comment]
Looks like the api key you are using is not correct. Can you double check it? 
Also bear in mind that depending on the api are you using (Future o spot) you need a different set of keys

**Comment by vaibhavbarmy** [comment]
Okay so the code is right?

In the API restriction, I have checked the following: 
1) Enable reading
2) Enable Spot and Margin trading
3) Enable Margin
4) Permit Universal Transfers
5) Permit Vanilla Options

but still getting the same error, am following this link to generate api key 
[](https://www.binance.com/en-IN/support/faq/360002502072)

is there another way to generate api key for spot trading?

**Comment by vaibhavbarmy** [comment]
https://www.binance.com/en-IN/support/faq/360002502072

**Comment by paoloboni** [comment]
Are you using the testnet? If so, the keys are different from those you use for the prod network.

**Comment by vaibhavbarmy** [comment]
Will the test net api key fetch correct binance wallet balance?
Because am able to get my USDT binance wallet balance using this api key through our binance scala client.

Regardless, Can you share me the resource or any document to create prod network api key, I couldn't find it directly through search

Really appreciate your timely responses, can you for least add a working code snippet to create spot order in line with the one shared in README.md

`

    
    BinanceClient.createSpotClient[IO](config)
      .use { client =>
        Stream
          .awakeEvery[IO](5.seconds)
          .repeat
          .evalMap(_ => client.getPrices())
          .evalMap(prices => log.info("Current prices: " + prices))
          .compile
          .drain
      }
      .redeem(
        { t =>
          log.error("Something went wrong", t)
          ExitCode(1)
        },
        _ => ExitCode.Success
      )
  }
}

`

**Comment by paoloboni** [comment]
For the testnet, use this page to get the keys: https://testnet.binance.vision/
To answer your question (read the FAQ "How to I get funds in/out of the Spot Test Network?"):
> All users registering on the Spot Test Network automatically receive a balance in many different assets. Please note that these are not real assets and can be used only on the Spot Test Network itself.

So don't expect to see your prod balance when using the testnet.

The document you linked above seems to have the correct procedure to get api-keys for prod.

This is an example of an app that creates an order:
```scala
import cats.effect.{ExitCode, IO, IOApp}
import io.github.paoloboni.binance.BinanceClient
import io.github.paoloboni.binance.common.{OrderSide, SpotConfig}
import io.github.paoloboni.binance.spot.parameters.SpotOrderCreateParams
import log.effect.LogWriter
import log.effect.fs2.SyncLogWriter.consoleLog

object PriceMonitor extends IOApp {

  val config = SpotConfig.Default(
    apiKey = "***",
    apiSecret = "***"
  )

  override def run(args: List[String]): IO[ExitCode] = {
    implicit val log: LogWriter[IO] = consoleLog[IO]

    BinanceClient
      .createSpotClient[IO](config)
      .use(
        _.createOrder(
          SpotOrderCreateParams
            .MARKET(
              symbol = "LTCUSDT",
              side = OrderSide.BUY,
              quantity = Some(0.5)
            )
        )
      )
      .redeem(
        { t =>
          log.error("Something went wrong", t)
          ExitCode(1)
        },
        _ => ExitCode.Success
      )
  }
}
```

Having a look at the end-to-end tests could be helpful too: https://github.com/paoloboni/binance-scala-client/tree/master/src/e2e/scala/io/github/paoloboni

**Comment by vaibhavbarmy** [comment]
Thanks a lot its working now, I have one last question suppose am using BTCUSDT pair, I want to buy BTC using USDT then in the quantity parameter I have to put USDT amount or BTC amount?

**Comment by vaibhavbarmy** [comment]
Thanks a lot for you help, am able to deploy my strategy live, cheers :)
One last help how do I disable debug and info level logs?

**Comment by paoloboni** [comment]
If you use console logger as in the example above, then you can do something like:
```scala
implicit val log: LogWriter[IO] = consoleLogUpToLevel(LogLevels.Warn)
```
or the level you want
