### ISSUE TITLE
Support depth update and order book snapshot websocket

### ISSUE THREAD

**Issue by Swoorup** [paoloboni/binance-scala-client#96]

**Comment by paoloboni** [comment]
Hi @Swoorup ,

Can you please provide some coordinates of the api you are referring to? Is this for both Spot and Future? Any link to Binance docs?

**Comment by Swoorup** [comment]
Hi @paoloboni 

Thank you for your response. I am referring to the public websocket subscriptions for orderbook snapshot and update as follows:

* https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#diff-depth-stream
* https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#all-book-tickers-stream
* https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams
