### ISSUE TITLE
ClassNotFoundException: com.google.protobuf.MessageLite

### ISSUE THREAD

**Issue by kincsescsaba** [paoloboni/binance-scala-client#98]
Hi,
I get the following exception with version 0.0.8:
`java.lang.ClassNotFoundException: com.google.protobuf.MessageLite`

Is there a recommended way to resolve this?

**Comment by paoloboni** [comment]
Hi,

Can you share the stacktrace?

**Comment by kincsescsaba** [comment]
Sure, here it is:

Abnormal build process termination: 
/usr/lib/jvm/java-11-openjdk/bin/java -Xmx700m -Djava.awt.headless=true -Djdt.compiler.useSingleThread=true -Dpreload.project.path=/home/kincsescsaba/IdeaProjects/action-signals -Dpreload.config.path=/home/kincsescsaba/.config/JetBrains/IdeaIC2021.1/options -Dcompile.parallel=false -Drebuild.on.dependency.change=true -Dio.netty.initialSeedUniquifier=5526974684559352992 -Dfile.encoding=UTF-8 -Duser.language=hu -Duser.country=HU -Didea.paths.selector=IdeaIC2021.1 -Didea.home.path=/usr/share/idea -Didea.config.path=/home/kincsescsaba/.config/JetBrains/IdeaIC2021.1 -Didea.plugins.path=/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1 -Djps.log.dir=/home/kincsescsaba/.cache/JetBrains/IdeaIC2021.1/log/build-log -Djps.fallback.jdk.home=/usr/lib/jvm/java-11-openjdk -Djps.fallback.jdk.version=11.0.11 -Dio.netty.noUnsafe=true -Djava.io.tmpdir=/home/kincsescsaba/.cache/JetBrains/IdeaIC2021.1/compile-server/action-signals_dc1c4dbc/_temp_ -Djps.backward.ref.index.builder=true -Dtmh.instrument.annotations=true -Dkotlin.incremental.compilation=true -Dkotlin.incremental.compilation.js=true -Dkotlin.daemon.enabled -Dkotlin.daemon.client.alive.path=\"/tmp/kotlin-idea-6391300349048850393-is-running\" -Dcompile.parallel.max.threads=4 -Dcompile.parallel=true --add-opens java.base/java.util=ALL-UNNAMED -classpath /usr/share/idea/plugins/java/lib/jps-launcher.jar org.jetbrains.jps.cmdline.Launcher /usr/share/idea/lib/asm-all-9.1.jar:/usr/share/idea/lib/slf4j.jar:/usr/share/idea/plugins/java/lib/jps-javac-extension-1.jar:/usr/share/idea/lib/jdom.jar:/usr/share/idea/lib/zip-signer.jar:/usr/share/idea/lib/annotations.jar:/usr/share/idea/lib/jna-platform.jar:/usr/share/idea/lib/kotlin-stdlib-jdk8.jar:/usr/share/idea/lib/intellij-deps-fastutil-8.5.2-6.jar:/usr/share/idea/plugins/java/lib/jps-builders.jar:/usr/share/idea/lib/qdox-2.0.0.jar:/usr/share/idea/lib/gson-2.8.6.jar:/usr/share/idea/lib/maven-resolver-provider.jar:/usr/share/idea/plugins/java/lib/jps-builders-6.jar:/usr/share/idea/plugins/java/lib/maven-resolver-connector-basic-1.3.3.jar:/usr/share/idea/plugins/java/lib/maven-resolver-transport-file-1.3.3.jar:/usr/share/idea/lib/commons-logging-1.2.jar:/usr/share/idea/lib/trove4j.jar:/usr/share/idea/lib/forms-1.1-preview.jar:/usr/share/idea/plugins/java/lib/javac2.jar:/usr/share/idea/lib/commons-lang3-3.10.jar:/usr/share/idea/plugins/java/lib/maven-resolver-transport-http-1.3.3.jar:/usr/share/idea/lib/http-client.jar:/usr/share/idea/lib/jna.jar:/usr/share/idea/lib/guava.jar:/usr/share/idea/lib/resources_en.jar:/usr/share/idea/lib/jps-model.jar:/usr/share/idea/lib/log4j.jar:/usr/share/idea/lib/netty-codec-http.jar:/usr/share/idea/lib/nanoxml-2.2.3.jar:/usr/share/idea/lib/platform-api.jar:/usr/share/idea/lib/netty-buffer.jar:/usr/share/idea/plugins/java/lib/aether-dependency-resolver.jar:/usr/share/idea/lib/idea_rt.jar:/usr/share/idea/lib/lz4-java-1.7.1.jar:/usr/share/idea/lib/oro-2.0.8.jar:/usr/share/idea/lib/util.jar:/usr/share/idea/lib/forms_rt.jar:/usr/share/idea/lib/plexus-utils-3.3.0.jar:/usr/share/idea/plugins/ant/lib/ant-jps.jar:/usr/share/idea/plugins/uiDesigner/lib/jps/java-guiForms-jps.jar:/usr/share/idea/plugins/eclipse/lib/eclipse-jps.jar:/usr/share/idea/plugins/eclipse/lib/eclipse-common.jar:/usr/share/idea/plugins/javaFX/lib/javaFX-jps.jar:/usr/share/idea/plugins/javaFX/lib/javaFX-common.jar:/usr/share/idea/plugins/IntelliLang/lib/java-langInjection-jps.jar:/usr/share/idea/plugins/Groovy/lib/groovy-jps.jar:/usr/share/idea/plugins/Groovy/lib/groovy-constants-rt.jar:/usr/share/idea/plugins/maven/lib/maven-jps.jar:/usr/share/idea/plugins/gradle-java/lib/gradle-jps.jar:/usr/share/idea/plugins/devkit/lib/devkit-jps.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/jps/kotlin-jps-plugin.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-stdlib.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-stdlib-jdk7.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-stdlib-jdk8.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-reflect.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-plugin.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-jps-common.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Kotlin/lib/kotlin-common.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/scala-library.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/compiler-shared.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/jps/nailgun.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/jps/compiler-jps.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/jps/sbt-interface.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/jps/incremental-compiler.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/jps/scala-parallel-collections.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/spray-json_2.13-1.3.5.jar:/home/kincsescsaba/.local/share/JetBrains/IdeaIC2021.1/Scala/lib/scala-compiler-indices-protocol_2.12-0.1.1.jar org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 33177 00f650ed-3262-4124-a4aa-5e909e2ed3a5 /home/kincsescsaba/.cache/JetBrains/IdeaIC2021.1/compile-server
Build process started. Classpath: /usr/share/idea/plugins/java/lib/jps-launcher.jarException in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.base/java.lang.reflect.Method.invoke(Method.java:566)	at org.jetbrains.jps.cmdline.Launcher.main(Launcher.java:43)Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/MessageLite	at org.jetbrains.jps.cmdline.BuildMain.main(BuildMain.java:94)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.MessageLite	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more

**Comment by kincsescsaba** [comment]
Rechecked, looks like Invalidate caches in the IDE solves the issue

**Comment by paoloboni** [comment]
@kincsescsaba I strongly suggest to use the latest version available

**Comment by kincsescsaba** [comment]
@paoloboni I used that version because I had a dependency issue in SBT and
downgrading to this seemed the fastest option

Paolo Boni ***@***.***> ezt írta (időpont: 2021. jún. 23.,
Sze, 11:00):
